Add Location Controller and Test
ucsb-cs156-s24/team01-s24-5pm-8 pull request #21
Opened 2024-04-19 01:35 UTC by spark686

- Added an endpoint /api/locations/get, which is used to get the name of the location. 
- Test coverage from jacoco: 
<img width="1135" alt="Screenshot 2024-04-18 at 6 27 04 PM" src="https://github.com/ucsb-cs156-s24/team01-s24-5pm-8/assets/122487506/c69e6eb6-ba89-4f2d-be3d-79f14a3b1fdd">

Please review and merge (#6)

Closes #7

2024-04-22 20:59 UTC, xinyao-song reviewed
LGTM, do you have a link to a dev deployment?

2024-04-23 08:32 UTC, bradygin requested changes
I believe this PR is trying to close the wrong issue. It says it's closing #7 when I think it should be closing #9? I could be wrong here, could someone double check?

2024-04-23 23:35 UTC, Hannahshakouri01 commented
LGTM, as Brady also mentioned, I think the only issue is that you should have closing #9, as #7 is for jokes.

2024-04-24 00:25 UTC, spark686 commented
I edited and included the swagger link ui

2024-04-24 00:35 UTC, merged